In [1]:
import pandas as pd
import numpy as np

In [2]:
from Library.simulate import chol_psd, near_psd, higham_psd, multi_norm_sim,PCA_sim

In [3]:

sigma = np.ones((5,5)) * 0.9
for i in range(0,5):
    sigma[i,i] = 1
L = chol_psd(sigma)
L

array([[1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.9       , 0.43588989, 0.        , 0.        , 0.        ],
       [0.9       , 0.20647416, 0.38388595, 0.        , 0.        ],
       [0.9       , 0.20647416, 0.12339191, 0.36351459, 0.        ],
       [0.9       , 0.20647416, 0.12339191, 0.08842247, 0.35259655]])

In [4]:
def gen_sigma(n):
    #generate sigma with different dimension
    sigma = np.ones((n,n)) * 0.9
    np.fill_diagonal(sigma, 1)
    sigma[0,1]=0.7357
    sigma[1,0]=0.7357
    return sigma

sigma = gen_sigma(5)
near_psd(sigma)



array([[1.        , 0.73570072, 0.89999652, 0.89999652, 0.89999652],
       [0.73570072, 1.        , 0.89999652, 0.89999652, 0.89999652],
       [0.89999652, 0.89999652, 1.        , 0.90000011, 0.90000011],
       [0.89999652, 0.89999652, 0.90000011, 1.        , 0.90000011],
       [0.89999652, 0.89999652, 0.90000011, 0.90000011, 1.        ]])

In [5]:
higham_psd(sigma, tol=0.1)

array([[1.        , 0.73570272, 0.89999825, 0.89999825, 0.89999825],
       [0.73570272, 1.        , 0.89999825, 0.89999825, 0.89999825],
       [0.89999825, 0.89999825, 1.        , 0.90000112, 0.90000112],
       [0.89999825, 0.89999825, 0.90000112, 1.        , 0.90000112],
       [0.89999825, 0.89999825, 0.90000112, 0.90000112, 1.        ]])

In [6]:
from Library.variance import ew_cov

In [7]:
data = pd.read_csv('Week03/DailyReturn.csv')
ewcov = ew_cov(data.values[:, 1:], lambda_=0.97)
ewcov

array([[8.41106909e-05, 1.06945662e-04, 1.21760871e-04, ...,
        1.25484463e-04, 8.11331555e-05, 8.61130395e-05],
       [1.06945662e-04, 2.68752303e-04, 1.97531665e-04, ...,
        1.15658764e-04, 3.74977522e-05, 8.22220854e-05],
       [1.21760871e-04, 1.97531665e-04, 2.91157502e-04, ...,
        8.30278956e-05, 3.31844912e-05, 7.34713753e-05],
       ...,
       [1.25484463e-04, 1.15658764e-04, 8.30278956e-05, ...,
        7.47889224e-04, 2.68371109e-04, 2.00639601e-04],
       [8.11331555e-05, 3.74977522e-05, 3.31844912e-05, ...,
        2.68371109e-04, 3.08241679e-04, 8.21009546e-05],
       [8.61130395e-05, 8.22220854e-05, 7.34713753e-05, ...,
        2.00639601e-04, 8.21009546e-05, 2.62692778e-04]])

In [8]:
direc_sim = multi_norm_sim(ewcov)
direc_sim

array([[ 0.00323515,  0.00522238,  0.01089786, ...,  0.00696706,
        -0.00795452, -0.01909612],
       [ 0.02179834, -0.00386284, -0.00811096, ...,  0.00815722,
        -0.00395968, -0.02154282],
       [ 0.02682903,  0.01277671,  0.01075878, ..., -0.00725294,
        -0.01790492, -0.01083308],
       ...,
       [ 0.02711625,  0.0177827 ,  0.01105353, ...,  0.01948122,
        -0.03342609, -0.02796094],
       [-0.02472552,  0.0057546 ,  0.02566186, ...,  0.01330215,
         0.00359858, -0.02787249],
       [-0.02173507, -0.00170061,  0.01843356, ...,  0.02668618,
        -0.02404652, -0.03089136]])

In [9]:
sim = PCA_sim(ewcov,exp = 0.75)
sim

array([[-0.00816602,  0.00925976,  0.00191371, ...,  0.00265306,
        -0.00095797, -0.01004138],
       [-0.00682438,  0.01602555,  0.00904676, ...,  0.00156645,
        -0.0112264 , -0.00215623],
       [ 0.00140036,  0.02315665, -0.00126747, ...,  0.01526437,
        -0.00985535, -0.00877747],
       ...,
       [-0.01674619,  0.0319062 ,  0.02890463, ..., -0.01502735,
        -0.00563361, -0.01718642],
       [-0.01243991,  0.01654009,  0.01209633, ..., -0.00869758,
         0.01985038, -0.01379374],
       [-0.00969853, -0.00540575,  0.00796531, ..., -0.00094378,
        -0.00111791, -0.03260173]])

In [10]:
from Library.risk_stats import return_calculate, var_calculate,es_calculate

In [11]:
price_data = pd.read_csv('Week04/DailyPrices.csv')

In [12]:
classic_return = return_calculate(price_data,method="CLASSIC", dateColumn="Date")
discrete_return = return_calculate(price_data,method="DISCRETE", dateColumn="Date")
log_return = return_calculate(price_data,method="LOG", dateColumn="Date")

In [13]:
discrete_return.head(10)

Date       SPY      AAPL      MSFT      AMZN      TSLA     GOOGL  \
0  2/15/2022 0:00  0.016127  0.023152  0.018542  0.008658  0.053291  0.007987   
1  2/16/2022 0:00  0.001121 -0.001389 -0.001167  0.010159  0.001041  0.008268   
2  2/17/2022 0:00 -0.021361 -0.021269 -0.029282 -0.021809 -0.050943 -0.037746   
3  2/18/2022 0:00 -0.006475 -0.009356 -0.009631 -0.013262 -0.022103 -0.016116   
4  2/22/2022 0:00 -0.010732 -0.017812 -0.000729 -0.015753 -0.041366 -0.004521   
5  2/23/2022 0:00 -0.017739 -0.025864 -0.025893 -0.035756 -0.069979 -0.017144   
6  2/24/2022 0:00  0.015049  0.016680  0.051093  0.045095  0.048073  0.039996   
7  2/25/2022 0:00  0.022064  0.012966  0.009233  0.016058  0.011364  0.013328   
8  2/28/2022 0:00 -0.002558  0.001638  0.004978 -0.001466  0.074777  0.004444   
9   3/1/2022 0:00 -0.015230 -0.011628 -0.012852 -0.015766 -0.006962 -0.007371   

       GOOG      META      NVDA  ...       PNC      MDLZ        MO       ADI  \
0  0.008319  0.015158  0.091812  ...  0.012807 -0.004082  0.004592  0.052344   
1  0.007784 -0.020181  0.000604  ...  0.006757 -0.002429  0.005763  0.038879   
2 -0.037669 -0.040778 -0.075591  ... -0.034949  0.005326  0.015017 -0.046988   
3 -0.013914 -0.007462 -0.035296  ... -0.000646 -0.000908  0.007203 -0.000436   
4 -0.008163 -0.019790 -0.010659  ...  0.009494  0.007121 -0.008891  0.003243   
5 -0.014045 -0.017963 -0.042882  ... -0.020041 -0.002859  0.013066 -0.027287   
6  0.039883  0.046107  0.060794  ... -0.017084 -0.024592 -0.045813  0.026071   
7  0.013914  0.013873  0.017223  ...  0.036092  0.032637  0.038531  0.014582   
8  0.002762  0.002613  0.009438  ... -0.016875 -0.019173 -0.003691 -0.011288   
9 -0.005360 -0.035729 -0.037236  ... -0.060527 -0.017410  0.005459 -0.020837   

       GILD       LMT       SYK        GM       TFC       TJX  
0  0.003600 -0.012275  0.033021  0.026240  0.028572  0.013237  
1  0.009294  0.012244  0.003363  0.015301 -0.001389 -0.025984  
2 -0.009855  0.004833 -0.030857 -0.031925 -0.033380 -0.028763  
3 -0.003916 -0.005942 -0.013674 -0.004506 -0.003677  0.015038  
4 -0.001147 -0.000673  0.008342 -0.037654 -0.002246 -0.013605  
5  0.006068  0.006991  0.013629 -0.008339 -0.025410 -0.042146  
6 -0.012062  0.017511  0.016087 -0.000647 -0.022937  0.035040  
7  0.008414  0.034824  0.031393  0.023301  0.063503  0.032308  
8 -0.011780  0.066660 -0.009180 -0.014969 -0.011910 -0.010183  
9 -0.002318  0.052582 -0.002772 -0.047089 -0.065413 -0.033283  

[10 rows x 101 columns]

In [14]:
log_return.head(10)

Date       SPY      AAPL      MSFT      AMZN      TSLA     GOOGL  \
0  2/15/2022 0:00  0.015998  0.022888  0.018372  0.008621  0.051919  0.007956   
1  2/16/2022 0:00  0.001120 -0.001390 -0.001168  0.010108  0.001040  0.008234   
2  2/17/2022 0:00 -0.021593 -0.021499 -0.029719 -0.022050 -0.052286 -0.038476   
3  2/18/2022 0:00 -0.006496 -0.009400 -0.009678 -0.013351 -0.022351 -0.016247   
4  2/22/2022 0:00 -0.010790 -0.017973 -0.000729 -0.015879 -0.042246 -0.004531   
5  2/23/2022 0:00 -0.017898 -0.026204 -0.026234 -0.036411 -0.072548 -0.017293   
6  2/24/2022 0:00  0.014937  0.016542  0.049831  0.044108  0.046954  0.039217   
7  2/25/2022 0:00  0.021824  0.012882  0.009191  0.015930  0.011300  0.013240   
8  2/28/2022 0:00 -0.002562  0.001636  0.004966 -0.001467  0.072114  0.004434   
9   3/1/2022 0:00 -0.015347 -0.011696 -0.012935 -0.015891 -0.006986 -0.007398   

       GOOG      META      NVDA  ...       PNC      MDLZ        MO       ADI  \
0  0.008284  0.015045  0.087839  ...  0.012726 -0.004091  0.004581  0.051021   
1  0.007754 -0.020387  0.000604  ...  0.006734 -0.002432  0.005747  0.038143   
2 -0.038397 -0.041632 -0.078601  ... -0.035574  0.005312  0.014905 -0.048128   
3 -0.014012 -0.007490 -0.035934  ... -0.000646 -0.000909  0.007177 -0.000436   
4 -0.008196 -0.019989 -0.010716  ...  0.009450  0.007096 -0.008930  0.003238   
5 -0.014145 -0.018127 -0.043828  ... -0.020245 -0.002863  0.012981 -0.027667   
6  0.039108  0.045076  0.059018  ... -0.017232 -0.024900 -0.046896  0.025737   
7  0.013818  0.013777  0.017076  ...  0.035456  0.032116  0.037808  0.014476   
8  0.002758  0.002610  0.009394  ... -0.017019 -0.019359 -0.003698 -0.011352   
9 -0.005374 -0.036383 -0.037947  ... -0.062436 -0.017563  0.005444 -0.021057   

       GILD       LMT       SYK        GM       TFC       TJX  
0  0.003594 -0.012351  0.032487  0.025901  0.028171  0.013150  
1  0.009251  0.012170  0.003357  0.015185 -0.001390 -0.026327  
2 -0.009903  0.004822 -0.031343 -0.032446 -0.033950 -0.029185  
3 -0.003924 -0.005960 -0.013768 -0.004517 -0.003684  0.014926  
4 -0.001147 -0.000673  0.008308 -0.038382 -0.002249 -0.013699  
5  0.006049  0.006967  0.013536 -0.008374 -0.025738 -0.043060  
6 -0.012135  0.017359  0.015959 -0.000647 -0.023204  0.034440  
7  0.008379  0.034231  0.030910  0.023034  0.061568  0.031797  
8 -0.011850  0.064532 -0.009222 -0.015083 -0.011982 -0.010235  
9 -0.002321  0.051246 -0.002776 -0.048234 -0.067651 -0.033849  

[10 rows x 101 columns]

In [15]:
meta = discrete_return['META']
var_calculate(meta,method='Normal')

0.06548547591311148

In [16]:
var_calculate(meta,method='Normal_EW')

0.09140156200276925

In [17]:
var_calculate(meta,method='Historic')

0.05224673019197934

In [18]:
var_calculate(meta,method='AR_1')

0.06546730090139895

In [19]:
var_calculate(meta,method='T')

0.05759600524783451

In [22]:
var, es = es_calculate(meta)
es

0.06915003792894078